@url_dev = http://localhost::3055/v1/api/

POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 12345678


{
    "name": "Shop TIPS",
    "email": "shoptipjs012@gmail.com"
    "password": 12345
}